# Generated by Django 4.2.8 on 2023-12-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provenance', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('inventory_no', models.IntegerField()),
                ('tone', models.TextField(max_length=250)),
                ('length', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
