# Generated by Django 4.2.8 on 2023-12-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuneup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tune up Date')),
                ('service', models.CharField(choices=[('B', 'Bridge Adjustment'), ('T', 'Tuning'), ('S', 'String Replacement')], default='B', max_length=1)),
                ('violin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.violin')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
