# Generated by Django 4.2.8 on 2023-12-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='violin',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
